local H=dofile('tests/lib/detector_harness.lua')
H.test('one recognized Initial arms observation and eventually reports failure',function()
    local h,c=H.step(H.qstart()); H.eq(nil,c.failure)
    H.advance(4.9); H.eq(nil,c.failure)
    H.advance(0.2); H.eq(true,c.failure); H.eq(1,h.failure_counter)
end)
H.test('nine parallel timed out connections rotate only one generation',function()
    local h
    for i=1,9 do h=H.step(H.qstart()) end
    H.advance(6); H.eq(2,h.nstrategy); H.eq(nil,h.failure_counter)
end)
H.test('Retry is progress but cannot permanently silence the detector',function()
    local d=H.qstart(); local h,c=H.step(d)
    H.advance(4)
    H.step(H.udp(d.track,false,H.quic('retry')))
    H.advance(4); H.eq(nil,c.failure)
    H.advance(2); H.eq(true,c.failure); H.eq(1,h.failure_counter)
end)
H.test('repeated Retry does not continually extend the deadline',function()
    local d=H.qstart(); local _,c=H.step(d)
    for i=1,4 do H.advance(1); H.step(H.udp(d.track,false,H.quic('retry'))) end
    H.advance(3); H.eq(true,c.failure)
end)
H.test('repeated Initial replies are not native two-packet success',function()
    local d=H.qstart(); local _,c=H.step(d)
    for i=1,3 do H.step(H.udp(d.track,false,H.quic('initial'),nil,1,i)) end
    H.eq(nil,c.nocheck); H.advance(6); H.eq(true,c.failure)
end)
H.test('wrong CID, garbage and truncated replies cannot rearm observation',function()
    local d=H.qstart(); local _,c=H.step(d)
    H.advance(4)
    for _,p in ipairs({'garbage',H.quic('initial','wrongcid'),H.quic('initial'):sub(1,10)}) do H.step(H.udp(d.track,false,p)) end
    H.advance(2); H.eq(true,c.failure)
end)
H.test('bidirectional short traffic ends observation and resets failures',function()
    local d=H.qstart(); local h,c=H.step(d); h.failure_counter=2
    H.step(H.udp(d.track,false,H.quic('initial')..H.quic('handshake')..H.quic('short')))
    H.step(H.udp(d.track,true,H.quic('short','serverid')))
    H.eq(true,c.nocheck); H.eq(nil,c.failure); H.eq(nil,h.failure_counter)
    H.advance(20); H.eq(nil,h.failure_counter); H.eq(1,h.nstrategy)
end)
H.test('one-direction short traffic still times out',function()
    local d=H.qstart(); local _,c=H.step(d)
    H.step(H.udp(d.track,false,H.quic('initial')..H.quic('short')))
    H.advance(6); H.eq(true,c.failure)
end)
H.test('v2 packet-type mapping works for coalesced server flight',function()
    local v=0x6b3343cf; local d=H.qstart(nil,v); local _,c=H.step(d)
    H.step(H.udp(d.track,false,H.quic('initial',nil,nil,v)..H.quic('handshake',nil,nil,v)..H.quic('short')))
    H.step(H.udp(d.track,true,H.quic('short','serverid')))
    H.eq(true,c.nocheck); H.eq(nil,c.failure)
end)
H.test('phase progress cannot exceed the absolute handshake budget',function()
    local d=H.qstart(); local _,c=H.step(d)
    for _,kind in ipairs({'retry','initial','handshake'}) do
        H.advance(4); H.step(H.udp(d.track,false,H.quic(kind)))
    end
    H.advance(2); H.eq(nil,c.failure)
    H.advance(2); H.eq(true,c.failure)
end)
H.test('old timer cannot change manual/final selection',function()
    local h,c=H.step(H.qstart()); h.nstrategy=2; h.final=2
    H.advance(6); H.eq(nil,c.failure); H.eq(2,h.nstrategy)
end)
H.test('timer does not revive after a full strategy circle',function()
    local h,c=H.step(H.qstart())
    for i=1,3 do circular_rotate(h) end
    H.advance(6); H.eq(nil,c.failure); H.eq(1,h.nstrategy)
end)
H.test('new connection uses a separate timer even with reused tuple',function()
    local d=H.qstart(); local h=H.step(d); H.advance(1)
    H.step(H.qstart()); H.advance(4.1); H.eq(1,h.failure_counter)
    H.advance(1); H.eq(2,h.failure_counter)
end)
H.test('unsupported versions retain native failure and success counters',function()
    local initial=H.quic('initial'):sub(1,4)..string.char(99)..H.quic('initial'):sub(6)
    local d=H.udp(nil,true,initial,'quic_initial',1,0); local h,c=H.step(d)
    H.step(H.udp(d.track,true,initial,'quic_initial',5,0))
    H.eq(true,c.failure); H.eq(1,h.failure_counter)
    local other=H.udp(nil,true,initial,'quic_initial'); local _,cc=H.step(other)
    H.step(H.udp(other.track,false,'response',nil,1,2)); H.eq(true,cc.nocheck); H.eq(nil,cc.failure)
end)
H.test('other UDP pools retain the native detector',function()
    local d=H.udp(nil,true,'stun',nil,5,0); d.arg.key='discord_udp'
    local _,c=H.step(d); H.eq(true,c.failure)
end)
H.test('capture exhaustion is neutral and cancels the timeout in either direction',function()
    for _,out in ipairs({false,true}) do
        local d=H.qstart(); local h,c=H.step(d); h.failure_counter=1
        H.step(H.udp(d.track,out,H.quic('initial',out and 'serverid' or nil),nil,8,8))
        H.eq(true,c.neutral); H.advance(20); H.eq(nil,c.failure); H.eq(1,h.failure_counter)
        H.reset()
    end
end)
H.test('configured capture limit is honored; success on the last packet wins',function()
    local d=H.qstart(); local _,c=H.step(d)
    local reply=H.udp(d.track,false,H.quic('initial'),nil,1,3); reply.arg.quic_in_limit='3'
    H.step(reply); H.eq(true,c.neutral)
    H.reset(); d=H.qstart(); local h; h,c=H.step(d)
    H.step(H.udp(d.track,false,H.quic('initial')..H.quic('short')))
    H.step(H.udp(d.track,true,H.quic('short','serverid'),nil,8,1))
    H.eq(nil,c.neutral); H.eq(true,c.nocheck); H.advance(20); H.eq(nil,h.failure_counter)
end)
H.finish()
